odoo.db:
  container_name: odoo.db
  hostname: odoo-db
  image: postgres:9.5
  restart: always
  volumes:
   - ../volumes/db:/var/lib/postgresql/data
  environment:
   - POSTGRES_USER=odoouser
   - POSTGRES_PASSWORD=zayth123

odoo.app:
  container_name: odoo.app
  hostname: odoo-app
  image: zaytech/odoo8_l10nbr_app
  restart: always
  volumes:
   - ../volumes/odoo:/opt/odoo
  links:
    - odoo.db:db

odoo.proxy:
  container_name: odoo.proxy
  hostname: proxy
  image: nginx
  restart: always
  volumes:
   - ../volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
   - ../volumes/nginx:/var/nginx
   - ../volumes/nginx/www:/var/www/
  ports:
   - "80:80"
  links:
    - odoo.db:odoo.db
    - odoo.app:odoo.app
