odoo.db:
  container_name: odoo.db
  hostname: odoo-db
  image: postgres:9.5
  volumes:
   - ../volumes/db:/var/lib/postgresql/data
  environment:
   - POSTGRES_USER=odoouser
   - POSTGRES_PASSWORD=zayth123

odoo.app:
  container_name: odoo.app
  hostname: odoo-app
  image: zaytech/odoo8_l10nbr:1.0.3
  volumes:
   - ../volumes/odoo/odoo.conf:/opt/odoo/odoo.conf
   - ../volumes/odoo/private:/opt/odoo/private
   - ../volumes/odoo/var:/opt/odoo/var
   - ../volumes/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf
  links:
    - odoo.db:db

odoo.proxy:
  container_name: odoo.proxy
  hostname: proxy
  image: nginx
  #restart: always
  volumes:
   - ../volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
   - ../volumes/nginx/confs.d:/var/nginx/confs.d
   - ../volumes/nginx/www:/var/www/
  ports:
   - "80:80"
  links:
    - odoo.db:odoo.db
    - odoo.app:odoo.app
